services:

  mysql:
    image: mysql:8.4
    container_name: assembleia-mysql

    environment:
      MYSQL_DATABASE: assembleiadb
      MYSQL_USER: assembleia
      MYSQL_PASSWORD: assembleia
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docs/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql

  api:
    build: .
    container_name: assembleia-api

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:mysql://mysql:3306/assembleiadb
      DB_USER: assembleia
      DB_PASSWORD: assembleia
      USER_INFO_URL: http://mock-user-info:8081

    depends_on:
      - mysql
      - mock-user-info

  mock-user-info:
    build: ./mock-user-info
    container_name: mock-user-info

    ports:
      - "8081:8081"

volumes:
  mysql_data: