CREATE TABLE ASSOCIADO(
    ID BINARY(16) PRIMARY KEY,
    CPF VARCHAR(14),
    NOME VARCHAR(120)
);

CREATE TABLE PAUTA(
    ID BINARY(16) PRIMARY KEY,
    NOME_PAUTA VARCHAR(50),
    TOTAL_VOTOS LONG,
    TOTAL_SIM LONG,
    TOTAL_NAO LONG,
    RESULTADO_PAUTA ENUM('APROVADA','REPROVADA','EMPATE')
);

CREATE TABLE VOTO(
    PAUTA_ID BINARY(16),
    ASSOCIADO_ID BINARY(16),
    OPCAO ENUM('SIM', 'NAO'),

    PRIMARY KEY(PAUTA_ID, ASSOCIADO_ID),

    CONSTRAINT FK_VOTO_PAUTA
        FOREIGN KEY(PAUTA_ID)
            REFERENCES PAUTA(ID),

    CONSTRAINT FK_VOTO_ASSOCIADO
        FOREIGN KEY (ASSOCIADO_ID)
            REFERENCES ASSOCIADO(ID)
);

CREATE TABLE SESSAO_VOTACAO(
    ID INT auto_increment,
    DATA_ABERTURA DATETIME,
    DATA_FECHAMENTO DATETIME,
    DURACAO LONG,
    SESSAO_STATUS ENUM('ABERTA','ENCERRADA'),
    PAUTA_ID BINARY(16),

    PRIMARY KEY (ID),
    CONSTRAINT FK_SESSAO_VOTACAO_PAUTA
       FOREIGN KEY (PAUTA_ID) REFERENCES PAUTA(ID)
);